### PR TITLE
Fix handling of newline at beginning of literal template

### LINKED ISSUE #93: Leading CR/LF is lost after Render()
A string starting with a newline will lose the newline in the rendered template.

Repro:

```
string text = Environment.NewLine + "something invariant";
Template template = new Template(text, '«', '»');            
if (!text.Equals(template.Render())) throw new Exception("Text not invariant.");

```

This is using "Antlr4.StringTemplate" C# package from nuget, version=4.0.6.9004 (running on Windows)

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #93

### CODE REVIEW

File: src/org/stringtemplate/v4/Interpreter.java [hunk 1]
```diff
@@ -414,7 +414,8 @@ protected int _exec(STWriter out, InstanceScope scope) {
 					break;
 				case Bytecode.INSTR_NEWLINE :
 					try {
-						if ( prevOpcode==Bytecode.INSTR_NEWLINE ||
+						if ( (prevOpcode==0 && !self.isAnonSubtemplate() && !self.impl.isRegion) ||
```
Comment (sharwell) [inline src/org/stringtemplate/v4/Interpreter.java]: :thought_balloon: I find it strange that `Misc.trimOneStartingNewline` and `Misc.trimOneTrailingNewline` are used for template definitions, but not for regions or anonymous subtemplates. It seems like we could simplify the new condition to just `prevOpcode==0` if we applied the trim operation to subtemplates.
